.BMPFILES = Stand.bmp \
	    StandJump1.bmp \
	    StandJump2.bmp \
	    StandJump3.bmp \
	    Walk1.bmp \
	    Walk2.bmp \
	    Walk3.bmp \
	    Walk4.bmp \
	    Walk5.bmp \
	    Walk6.bmp \
	    Walk7.bmp \
	    Walk8.bmp \
	    Walk9.bmp \
	    Run1.bmp \
	    Run2.bmp \
	    Run3.bmp \
	    Run4.bmp \
	    Run5.bmp \
	    Run6.bmp \
	    Run7.bmp \
	    Run8.bmp \
	    Run9.bmp \
	    Run10.bmp \
	    Run11.bmp \
	    Run12.bmp \
	    Run13.bmp \
	    Run14.bmp \
	    Run15.bmp \
	    Run16.bmp \
	    RunTurn1.bmp \
	    RunTurn2.bmp \
	    RunTurn3.bmp \
	    RunTurn4.bmp \
	    RunTurn5.bmp \
	    RunTurn6.bmp \
	    RunTurn7.bmp \
	    RunTurn8.bmp \
	    RunTurn9.bmp \
	    RunJump1.bmp \
	    RunJump2.bmp \
	    RunJump3.bmp \
	    JumpTop.bmp \
	    ButtBounce1.bmp \
	    ButtBounce2.bmp \
	    ButtBounce3.bmp \
	    ButtBounce4.bmp \
	    ButtBounce5.bmp \
	    Karate1.bmp \
	    Karate2.bmp \
	    Karate3.bmp \
	    Karate4.bmp
 
.CFILES = $(.BMPFILES:.bmp=.c)

.OFILES = $(.BMPFILES:.bmp=.o)

_AGBDIR = ($AGBDIR)

CFLAGS	= -g -O2 -I$(AGBDIR)/include -mthumb-interwork -nostdlib

TARGET_ARC = libSpongeBob_Sprs.a

$(TARGET_ARC): $(.OFILES)
	ar rcs $(TARGET_ARC) $(.OFILES)

Stand.c: Stand.bmp
	bmp2agb -o $@ $<
StandJump1.c: StandJump1.bmp
	bmp2agb -onp $@ $<
StandJump2.c: StandJump2.bmp
	bmp2agb -onp $@ $<
StandJump3.c: StandJump3.bmp
	bmp2agb -onp $@ $<
Walk1.c: Walk1.bmp
	bmp2agb -onp $@ $<
Walk2.c: Walk2.bmp
	bmp2agb -onp $@ $<
Walk3.c: Walk3.bmp
	bmp2agb -onp $@ $<
Walk4.c: Walk4.bmp
	bmp2agb -onp $@ $<
Walk5.c: Walk5.bmp
	bmp2agb -onp $@ $<
Walk6.c: Walk6.bmp
	bmp2agb -onp $@ $<
Walk7.c: Walk7.bmp
	bmp2agb -onp $@ $<
Walk8.c: Walk8.bmp
	bmp2agb -onp $@ $<
Walk9.c: Walk9.bmp
	bmp2agb -onp $@ $<
Run1.c: Run1.bmp
	bmp2agb -onp $@ $<
Run2.c: Run2.bmp
	bmp2agb -onp $@ $<
Run3.c: Run3.bmp
	bmp2agb -onp $@ $<
Run4.c: Run4.bmp
	bmp2agb -onp $@ $<
Run5.c: Run5.bmp
	bmp2agb -onp $@ $<
Run6.c: Run6.bmp
	bmp2agb -onp $@ $<
Run7.c: Run7.bmp
	bmp2agb -onp $@ $<
Run8.c: Run8.bmp
	bmp2agb -onp $@ $<
Run9.c: Run9.bmp
	bmp2agb -onp $@ $<
Run10.c: Run10.bmp
	bmp2agb -onp $@ $<
Run11.c: Run11.bmp 
	bmp2agb -onp $@ $<
Run12.c: Run12.bmp
	bmp2agb -onp $@ $<
Run13.c: Run13.bmp
	bmp2agb -onp $@ $<
Run14.c: Run14.bmp
	bmp2agb -onp $@ $<
Run15.c: Run15.bmp
	bmp2agb -onp $@ $<
Run16.c: Run16.bmp
	bmp2agb -onp $@ $<
RunTurn1.c: RunTurn1.bmp
	bmp2agb -onp $@ $<
RunTurn2.c: RunTurn2.bmp
	bmp2agb -onp $@ $<
RunTurn3.c: RunTurn3.bmp
	bmp2agb -onp $@ $<
RunTurn4.c: RunTurn4.bmp
	bmp2agb -onp $@ $<
RunTurn5.c: RunTurn5.bmp
	bmp2agb -onp $@ $<
RunTurn6.c: RunTurn6.bmp
	bmp2agb -onp $@ $<
RunTurn7.c: RunTurn7.bmp
	bmp2agb -onp $@ $<
RunTurn8.c: RunTurn8.bmp
	bmp2agb -onp $@ $<
RunTurn9.c: RunTurn9.bmp
	bmp2agb -onp $@ $<
RunJump1.c: RunJump1.bmp
	bmp2agb -onp $@ $<
RunJump2.c: RunJump2.bmp
	bmp2agb -onp $@ $<
RunJump3.c: RunJump3.bmp
	bmp2agb -onp $@ $<
JumpTop.c: JumpTop.bmp
	bmp2agb -onp $@ $<
ButtBounce1.c: ButtBounce1.bmp
	bmp2agb -onp $@ $<
ButtBounce2.c: ButtBounce2.bmp
	bmp2agb -onp $@ $<
ButtBounce3.c: ButtBounce3.bmp
	bmp2agb -onp $@ $<
ButtBounce4.c: ButtBounce4.bmp
	bmp2agb -onp $@ $<
ButtBounce5.c: ButtBounce5.bmp
	bmp2agb -onp $@ $<
Karate1.c: Karate1.bmp
	bmp2agb -onp $@ $<
Karate2.c: Karate2.bmp
	bmp2agb -onp $@ $<
Karate3.c: Karate3.bmp
	bmp2agb -onp $@ $<
Karate4.c: Karate4.bmp
	bmp2agb -onp $@ $<

clean:
	-rm $(TARGET_ARC) $(.OFILES) $(.CFILES)

