.BMPFILES = buttbounceend0001.bmp \
	buttbounceend0003.bmp \
	buttbounceend0005.bmp \
	buttbounceend0007.bmp \
	buttbouncestart0001.bmp \
	buttbouncestart0003.bmp \
	buttbouncestart0005.bmp \
	buttbouncestart0007.bmp \
	deathbackwards0001.bmp \
	deathbackwards0003.bmp \
	deathbackwards0005.bmp \
	deathbackwards0007.bmp \
	deathbackwards0009.bmp \
	deathbackwards0011.bmp \
	deathbackwards0013.bmp \
	deathbackwards0015.bmp \
	deathdry0001.bmp \
	deathdry0003.bmp \
	deathdry0005.bmp \
	deathdry0007.bmp \
	deathdry0009.bmp \
	deathdry0011.bmp \
	deathdry0013.bmp \
	deathdry0015.bmp \
	deathforwards0001.bmp \
	deathforwards0003.bmp \
	deathforwards0005.bmp \
	deathforwards0007.bmp \
	deathforwards0009.bmp \
	deathforwards0011.bmp \
	deathforwards0013.bmp \
	deathforwards0015.bmp \
	deathspin0001.bmp \
	deathspin0003.bmp \
	deathspin0005.bmp \
	deathspin0007.bmp \
	deathspin0009.bmp \
	deathspin0011.bmp \
	deathspin0013.bmp \
	deathspin0015.bmp \
	deathsquash0001.bmp \
	deathsquash0003.bmp \
	deathsquash0005.bmp \
	deathsquash0007.bmp \
	deathsquash0009.bmp \
	deathsquash0011.bmp \
	deathsquash0013.bmp \
	deathsquash0015.bmp \
	deathtar0001.bmp \
	deathtar0003.bmp \
	deathtar0005.bmp \
	deathtar0007.bmp \
	deathtarstart0001.bmp \
	deathtarstart0003.bmp \
	deathtarstart0005.bmp \
	deathtarstart0007.bmp \
	electricshock0001.bmp \
	electricshock0003.bmp \
	electricshock0005.bmp \
	electricshock0007.bmp \
	electricshockend0000.bmp \
	electricshockend0001.bmp \
	electricshockstart0000.bmp \
	electricshockstart0001.bmp \
	faceback0001.bmp \
	faceback0003.bmp \
	faceback0005.bmp \
	faceback0007.bmp \
	facefront0000.bmp \
	facefront0001.bmp \
	fall0001.bmp \
	fall0003.bmp \
	fall0005.bmp \
	fireend0000.bmp \
	fireend0001.bmp \
	firestart0000.bmp \
	firestart0001.bmp \
	firestart0002.bmp \
	firestart0003.bmp \
	getup0001.bmp \
	getup0003.bmp \
	getup0005.bmp \
	getup0007.bmp \
	getuprun0001.bmp \
	getuprun0003.bmp \
	getuprun0005.bmp \
	getuprun0007.bmp \
	hitground0001.bmp \
	hitground0003.bmp \
	hitground0005.bmp \
	hitground0007.bmp \
	hover0001.bmp \
	hover0003.bmp \
	hover0005.bmp \
	hover0007.bmp \
	hoverend0000.bmp \
	hoverend0001.bmp \
	hoverstart0000.bmp \
	hoverstart0001.bmp \
	idlebouncehead0001.bmp \
	idlebouncehead0003.bmp \
	idlebouncehead0005.bmp \
	idlebouncehead0007.bmp \
	idlebouncehead0009.bmp \
	idlebouncehead0011.bmp \
	idlebouncehead0013.bmp \
	idlebouncehead0015.bmp \
	idlebounceheadend0001.bmp \
	idlebounceheadend0003.bmp \
	idlebounceheadend0005.bmp \
	idlebounceheadend0007.bmp \
	idlebounceheadstart0001.bmp \
	idlebounceheadstart0003.bmp \
	idlebounceheadstart0005.bmp \
	idlebounceheadstart0007.bmp \
	idlebreathe0000.bmp \
	idlebreathe0001.bmp \
	idlebreathe0002.bmp \
	idlebreathe0003.bmp \
	idlefaces0001.bmp \
	idlefaces0003.bmp \
	idlefaces0005.bmp \
	idlefaces0007.bmp \
	idlefacesend0001.bmp \
	idlefacesend0003.bmp \
	idlefacesend0005.bmp \
	idlefacesend0007.bmp \
	idlefacesstart0000.bmp \
	idlefacesstart0001.bmp \
	idlehoola0001.bmp \
	idlehoola0003.bmp \
	idlehoola0005.bmp \
	idlehoola0007.bmp \
	idlehoola0009.bmp \
	idlehoola0011.bmp \
	idlehoola0013.bmp \
	idlehoola0015.bmp \
	idlekarate0001.bmp \
	idlekarate0003.bmp \
	idlekarate0005.bmp \
	idlekarate0007.bmp \
	idlekarate0009.bmp \
	idlekarate0011.bmp \
	idlekarate0013.bmp \
	idlekarate0015.bmp \
	idlesleep0001.bmp \
	idlesleep0003.bmp \
	idlesleep0005.bmp \
	idlesleep0007.bmp \
	idlesleepend0001.bmp \
	idlesleepend0003.bmp \
	idlesleepstart0001.bmp \
	idlesleepstart0003.bmp \
	idlesplitpants0001.bmp \
	idlesplitpants0003.bmp \
	idlesplitpants0005.bmp \
	idlesplitpants0007.bmp \
	idlesplitpants0009.bmp \
	idlesplitpants0011.bmp \
	idlesplitpants0013.bmp \
	idlesplitpants0015.bmp \
	idlesplitpants0017.bmp \
	idlesplitpants0019.bmp \
	idlesplitpants0021.bmp \
	idlesplitpants0023.bmp \
	idleweapon0001.bmp \
	idleweapon0003.bmp \
	idleweapon0005.bmp \
	idleweapon0007.bmp \
	idleweapon0009.bmp \
	idleweapon0011.bmp \
	idleweapon0013.bmp \
	idleweapon0015.bmp \
	idlewigglearms0001.bmp \
	idlewigglearms0003.bmp \
	idlewigglearms0005.bmp \
	idlewigglearms0007.bmp \
	idlewigglearms0009.bmp \
	idlewigglearms0011.bmp \
	idlewigglearms0013.bmp \
	idlewigglearms0015.bmp \
	idlewind0001.bmp \
	idlewind0003.bmp \
	idlewind0005.bmp \
	idlewind0007.bmp \
	idlewind0009.bmp \
	idlewind0011.bmp \
	idlewind0013.bmp \
	idlewind0015.bmp \
	jumpend0001.bmp \
	jumpend0003.bmp \
	karate0001.bmp \
	karate0003.bmp \
	karate0005.bmp \
	karate0007.bmp \
	karate0009.bmp \
	karate0011.bmp \
	karate0013.bmp \
	karate0015.bmp \
	netfirelob0001.bmp \
	netfirelob0003.bmp \
	netfirelob0005.bmp \
	netfirelob0007.bmp \
	netfirelob0009.bmp \
	netfirelob0011.bmp \
	netfirelob0013.bmp \
	netfirelob0015.bmp \
	netswipe0001.bmp \
	netswipe0003.bmp \
	netswipe0005.bmp \
	netswipe0007.bmp \
	netswipe0009.bmp \
	netswipe0011.bmp \
	netswipe0013.bmp \
	netswipe0015.bmp \
	run0000.bmp \
	run0001.bmp \
	run0002.bmp \
	run0003.bmp \
	run0004.bmp \
	run0005.bmp \
	run0006.bmp \
	run0007.bmp \
	run0008.bmp \
	run0009.bmp \
	run0010.bmp \
	run0011.bmp \
	run0012.bmp \
	run0013.bmp \
	run0014.bmp \
	run0015.bmp \
	soakup0001.bmp \
	soakup0003.bmp \
	soakup0005.bmp \
	soakup0007.bmp \
	teeterfront0001.bmp \
	teeterfront0003.bmp \
	teeterfront0005.bmp \
	teeterfront0007.bmp \
	teeterfront0009.bmp \
	teeterfront0011.bmp \
	teeterfront0013.bmp \
	teeterfront0015.bmp \
	walkforward0001.bmp \
	walkforward0003.bmp \
	walkforward0005.bmp \
	walkforward0007.bmp \
	walkforward0009.bmp \
	walkforward0011.bmp \
	walkforward0013.bmp \
	walkforward0015.bmp
 
.CFILES = $(.BMPFILES:.bmp=_RL.c)

.OFILES = $(.BMPFILES:.bmp=_RL.o)

_AGBDIR = ($AGBDIR)

CFLAGS	= -g -O2 -I$(AGBDIR)/include -mthumb-interwork -nostdlib

TARGET_ARC = libSpongeBob_Sprs.a

$(TARGET_ARC): $(.OFILES)
	ar rcs $(TARGET_ARC) $(.OFILES)

BMP2AGB := bmp2agb -onpr

buttbounceend0001_RL.c: buttbounceend0001.bmp
	$(BMP2AGB) $@ $<
buttbounceend0003_RL.c: buttbounceend0003.bmp
	$(BMP2AGB) $@ $<
buttbounceend0005_RL.c: buttbounceend0005.bmp
	$(BMP2AGB) $@ $<
buttbounceend0007_RL.c: buttbounceend0007.bmp
	$(BMP2AGB) $@ $<
buttbouncestart0001_RL.c: buttbouncestart0001.bmp
	$(BMP2AGB) $@ $<
buttbouncestart0003_RL.c: buttbouncestart0003.bmp
	$(BMP2AGB) $@ $<
buttbouncestart0005_RL.c: buttbouncestart0005.bmp
	$(BMP2AGB) $@ $<
buttbouncestart0007_RL.c: buttbouncestart0007.bmp
	$(BMP2AGB) $@ $<
deathbackwards0001_RL.c: deathbackwards0001.bmp
	$(BMP2AGB) $@ $<
deathbackwards0003_RL.c: deathbackwards0003.bmp
	$(BMP2AGB) $@ $<
deathbackwards0005_RL.c: deathbackwards0005.bmp
	$(BMP2AGB) $@ $<
deathbackwards0007_RL.c: deathbackwards0007.bmp
	$(BMP2AGB) $@ $<
deathbackwards0009_RL.c: deathbackwards0009.bmp
	$(BMP2AGB) $@ $<
deathbackwards0011_RL.c: deathbackwards0011.bmp
	$(BMP2AGB) $@ $<
deathbackwards0013_RL.c: deathbackwards0013.bmp
	$(BMP2AGB) $@ $<
deathbackwards0015_RL.c: deathbackwards0015.bmp
	$(BMP2AGB) $@ $<
deathdry0001_RL.c: deathdry0001.bmp
	$(BMP2AGB) $@ $<
deathdry0003_RL.c: deathdry0003.bmp
	$(BMP2AGB) $@ $<
deathdry0005_RL.c: deathdry0005.bmp
	$(BMP2AGB) $@ $<
deathdry0007_RL.c: deathdry0007.bmp
	$(BMP2AGB) $@ $<
deathdry0009_RL.c: deathdry0009.bmp
	$(BMP2AGB) $@ $<
deathdry0011_RL.c: deathdry0011.bmp
	$(BMP2AGB) $@ $<
deathdry0013_RL.c: deathdry0013.bmp
	$(BMP2AGB) $@ $<
deathdry0015_RL.c: deathdry0015.bmp
	$(BMP2AGB) $@ $<
deathforwards0001_RL.c: deathforwards0001.bmp
	$(BMP2AGB) $@ $<
deathforwards0003_RL.c: deathforwards0003.bmp
	$(BMP2AGB) $@ $<
deathforwards0005_RL.c: deathforwards0005.bmp
	$(BMP2AGB) $@ $<
deathforwards0007_RL.c: deathforwards0007.bmp
	$(BMP2AGB) $@ $<
deathforwards0009_RL.c: deathforwards0009.bmp
	$(BMP2AGB) $@ $<
deathforwards0011_RL.c: deathforwards0011.bmp
	$(BMP2AGB) $@ $<
deathforwards0013_RL.c: deathforwards0013.bmp
	$(BMP2AGB) $@ $<
deathforwards0015_RL.c: deathforwards0015.bmp
	$(BMP2AGB) $@ $<
deathspin0001_RL.c: deathspin0001.bmp
	$(BMP2AGB) $@ $<
deathspin0003_RL.c: deathspin0003.bmp
	$(BMP2AGB) $@ $<
deathspin0005_RL.c: deathspin0005.bmp
	$(BMP2AGB) $@ $<
deathspin0007_RL.c: deathspin0007.bmp
	$(BMP2AGB) $@ $<
deathspin0009_RL.c: deathspin0009.bmp
	$(BMP2AGB) $@ $<
deathspin0011_RL.c: deathspin0011.bmp
	$(BMP2AGB) $@ $<
deathspin0013_RL.c: deathspin0013.bmp
	$(BMP2AGB) $@ $<
deathspin0015_RL.c: deathspin0015.bmp
	$(BMP2AGB) $@ $<
deathsquash0001_RL.c: deathsquash0001.bmp
	$(BMP2AGB) $@ $<
deathsquash0003_RL.c: deathsquash0003.bmp
	$(BMP2AGB) $@ $<
deathsquash0005_RL.c: deathsquash0005.bmp
	$(BMP2AGB) $@ $<
deathsquash0007_RL.c: deathsquash0007.bmp
	$(BMP2AGB) $@ $<
deathsquash0009_RL.c: deathsquash0009.bmp
	$(BMP2AGB) $@ $<
deathsquash0011_RL.c: deathsquash0011.bmp
	$(BMP2AGB) $@ $<
deathsquash0013_RL.c: deathsquash0013.bmp
	$(BMP2AGB) $@ $<
deathsquash0015_RL.c: deathsquash0015.bmp
	$(BMP2AGB) $@ $<
deathtar0001_RL.c: deathtar0001.bmp
	$(BMP2AGB) $@ $<
deathtar0003_RL.c: deathtar0003.bmp
	$(BMP2AGB) $@ $<
deathtar0005_RL.c: deathtar0005.bmp
	$(BMP2AGB) $@ $<
deathtar0007_RL.c: deathtar0007.bmp
	$(BMP2AGB) $@ $<
deathtarstart0001_RL.c: deathtarstart0001.bmp
	$(BMP2AGB) $@ $<
deathtarstart0003_RL.c: deathtarstart0003.bmp
	$(BMP2AGB) $@ $<
deathtarstart0005_RL.c: deathtarstart0005.bmp
	$(BMP2AGB) $@ $<
deathtarstart0007_RL.c: deathtarstart0007.bmp
	$(BMP2AGB) $@ $<
electricshock0001_RL.c: electricshock0001.bmp
	$(BMP2AGB) $@ $<
electricshock0003_RL.c: electricshock0003.bmp
	$(BMP2AGB) $@ $<
electricshock0005_RL.c: electricshock0005.bmp
	$(BMP2AGB) $@ $<
electricshock0007_RL.c: electricshock0007.bmp
	$(BMP2AGB) $@ $<
electricshockend0000_RL.c: electricshockend0000.bmp
	$(BMP2AGB) $@ $<
electricshockend0001_RL.c: electricshockend0001.bmp
	$(BMP2AGB) $@ $<
electricshockstart0000_RL.c: electricshockstart0000.bmp
	$(BMP2AGB) $@ $<
electricshockstart0001_RL.c: electricshockstart0001.bmp
	$(BMP2AGB) $@ $<
faceback0001_RL.c: faceback0001.bmp
	$(BMP2AGB) $@ $<
faceback0003_RL.c: faceback0003.bmp
	$(BMP2AGB) $@ $<
faceback0005_RL.c: faceback0005.bmp
	$(BMP2AGB) $@ $<
faceback0007_RL.c: faceback0007.bmp
	$(BMP2AGB) $@ $<
facefront0000_RL.c: facefront0000.bmp
	$(BMP2AGB) $@ $<
facefront0001_RL.c: facefront0001.bmp
	$(BMP2AGB) $@ $<
fall0001_RL.c: fall0001.bmp
	$(BMP2AGB) $@ $<
fall0003_RL.c: fall0003.bmp
	$(BMP2AGB) $@ $<
fall0005_RL.c: fall0005.bmp
	$(BMP2AGB) $@ $<
fireend0000_RL.c: fireend0000.bmp
	$(BMP2AGB) $@ $<
fireend0001_RL.c: fireend0001.bmp
	$(BMP2AGB) $@ $<
firestart0000_RL.c: firestart0000.bmp
	$(BMP2AGB) $@ $<
firestart0001_RL.c: firestart0001.bmp
	$(BMP2AGB) $@ $<
firestart0002_RL.c: firestart0002.bmp
	$(BMP2AGB) $@ $<
firestart0003_RL.c: firestart0003.bmp
	$(BMP2AGB) $@ $<
getup0001_RL.c: getup0001.bmp
	$(BMP2AGB) $@ $<
getup0003_RL.c: getup0003.bmp
	$(BMP2AGB) $@ $<
getup0005_RL.c: getup0005.bmp
	$(BMP2AGB) $@ $<
getup0007_RL.c: getup0007.bmp
	$(BMP2AGB) $@ $<
getuprun0001_RL.c: getuprun0001.bmp
	$(BMP2AGB) $@ $<
getuprun0003_RL.c: getuprun0003.bmp
	$(BMP2AGB) $@ $<
getuprun0005_RL.c: getuprun0005.bmp
	$(BMP2AGB) $@ $<
getuprun0007_RL.c: getuprun0007.bmp
	$(BMP2AGB) $@ $<
hitground0001_RL.c: hitground0001.bmp
	$(BMP2AGB) $@ $<
hitground0003_RL.c: hitground0003.bmp
	$(BMP2AGB) $@ $<
hitground0005_RL.c: hitground0005.bmp
	$(BMP2AGB) $@ $<
hitground0007_RL.c: hitground0007.bmp
	$(BMP2AGB) $@ $<
hover0001_RL.c: hover0001.bmp
	$(BMP2AGB) $@ $<
hover0003_RL.c: hover0003.bmp
	$(BMP2AGB) $@ $<
hover0005_RL.c: hover0005.bmp
	$(BMP2AGB) $@ $<
hover0007_RL.c: hover0007.bmp
	$(BMP2AGB) $@ $<
hoverend0000_RL.c: hoverend0000.bmp
	$(BMP2AGB) $@ $<
hoverend0001_RL.c: hoverend0001.bmp
	$(BMP2AGB) $@ $<
hoverstart0000_RL.c: hoverstart0000.bmp
	$(BMP2AGB) $@ $<
hoverstart0001_RL.c: hoverstart0001.bmp
	$(BMP2AGB) $@ $<
idlebouncehead0001_RL.c: idlebouncehead0001.bmp
	$(BMP2AGB) $@ $<
idlebouncehead0003_RL.c: idlebouncehead0003.bmp
	$(BMP2AGB) $@ $<
idlebouncehead0005_RL.c: idlebouncehead0005.bmp
	$(BMP2AGB) $@ $<
idlebouncehead0007_RL.c: idlebouncehead0007.bmp
	$(BMP2AGB) $@ $<
idlebouncehead0009_RL.c: idlebouncehead0009.bmp
	$(BMP2AGB) $@ $<
idlebouncehead0011_RL.c: idlebouncehead0011.bmp
	$(BMP2AGB) $@ $<
idlebouncehead0013_RL.c: idlebouncehead0013.bmp
	$(BMP2AGB) $@ $<
idlebouncehead0015_RL.c: idlebouncehead0015.bmp
	$(BMP2AGB) $@ $<
idlebounceheadend0001_RL.c: idlebounceheadend0001.bmp
	$(BMP2AGB) $@ $<
idlebounceheadend0003_RL.c: idlebounceheadend0003.bmp
	$(BMP2AGB) $@ $<
idlebounceheadend0005_RL.c: idlebounceheadend0005.bmp
	$(BMP2AGB) $@ $<
idlebounceheadend0007_RL.c: idlebounceheadend0007.bmp
	$(BMP2AGB) $@ $<
idlebounceheadstart0001_RL.c: idlebounceheadstart0001.bmp
	$(BMP2AGB) $@ $<
idlebounceheadstart0003_RL.c: idlebounceheadstart0003.bmp
	$(BMP2AGB) $@ $<
idlebounceheadstart0005_RL.c: idlebounceheadstart0005.bmp
	$(BMP2AGB) $@ $<
idlebounceheadstart0007_RL.c: idlebounceheadstart0007.bmp
	$(BMP2AGB) $@ $<
idlebreathe0000_RL.c: idlebreathe0000.bmp
	$(BMP2AGB) $@ $<
idlebreathe0001_RL.c: idlebreathe0001.bmp
	$(BMP2AGB) $@ $<
idlebreathe0002_RL.c: idlebreathe0002.bmp
	$(BMP2AGB) $@ $<
idlebreathe0003_RL.c: idlebreathe0003.bmp
	$(BMP2AGB) $@ $<
idlefaces0001_RL.c: idlefaces0001.bmp
	$(BMP2AGB) $@ $<
idlefaces0003_RL.c: idlefaces0003.bmp
	$(BMP2AGB) $@ $<
idlefaces0005_RL.c: idlefaces0005.bmp
	$(BMP2AGB) $@ $<
idlefaces0007_RL.c: idlefaces0007.bmp
	$(BMP2AGB) $@ $<
idlefacesend0001_RL.c: idlefacesend0001.bmp
	$(BMP2AGB) $@ $<
idlefacesend0003_RL.c: idlefacesend0003.bmp
	$(BMP2AGB) $@ $<
idlefacesend0005_RL.c: idlefacesend0005.bmp
	$(BMP2AGB) $@ $<
idlefacesend0007_RL.c: idlefacesend0007.bmp
	$(BMP2AGB) $@ $<
idlefacesstart0000_RL.c: idlefacesstart0000.bmp
	$(BMP2AGB) $@ $<
idlefacesstart0001_RL.c: idlefacesstart0001.bmp
	$(BMP2AGB) $@ $<
idlehoola0001_RL.c: idlehoola0001.bmp
	$(BMP2AGB) $@ $<
idlehoola0003_RL.c: idlehoola0003.bmp
	$(BMP2AGB) $@ $<
idlehoola0005_RL.c: idlehoola0005.bmp
	$(BMP2AGB) $@ $<
idlehoola0007_RL.c: idlehoola0007.bmp
	$(BMP2AGB) $@ $<
idlehoola0009_RL.c: idlehoola0009.bmp
	$(BMP2AGB) $@ $<
idlehoola0011_RL.c: idlehoola0011.bmp
	$(BMP2AGB) $@ $<
idlehoola0013_RL.c: idlehoola0013.bmp
	$(BMP2AGB) $@ $<
idlehoola0015_RL.c: idlehoola0015.bmp
	$(BMP2AGB) $@ $<
idlekarate0001_RL.c: idlekarate0001.bmp
	$(BMP2AGB) $@ $<
idlekarate0003_RL.c: idlekarate0003.bmp
	$(BMP2AGB) $@ $<
idlekarate0005_RL.c: idlekarate0005.bmp
	$(BMP2AGB) $@ $<
idlekarate0007_RL.c: idlekarate0007.bmp
	$(BMP2AGB) $@ $<
idlekarate0009_RL.c: idlekarate0009.bmp
	$(BMP2AGB) $@ $<
idlekarate0011_RL.c: idlekarate0011.bmp
	$(BMP2AGB) $@ $<
idlekarate0013_RL.c: idlekarate0013.bmp
	$(BMP2AGB) $@ $<
idlekarate0015_RL.c: idlekarate0015.bmp
	$(BMP2AGB) $@ $<
idlesleep0001_RL.c: idlesleep0001.bmp
	$(BMP2AGB) $@ $<
idlesleep0003_RL.c: idlesleep0003.bmp
	$(BMP2AGB) $@ $<
idlesleep0005_RL.c: idlesleep0005.bmp
	$(BMP2AGB) $@ $<
idlesleep0007_RL.c: idlesleep0007.bmp
	$(BMP2AGB) $@ $<
idlesleepend0001_RL.c: idlesleepend0001.bmp
	$(BMP2AGB) $@ $<
idlesleepend0003_RL.c: idlesleepend0003.bmp
	$(BMP2AGB) $@ $<
idlesleepstart0001_RL.c: idlesleepstart0001.bmp
	$(BMP2AGB) $@ $<
idlesleepstart0003_RL.c: idlesleepstart0003.bmp
	$(BMP2AGB) $@ $<
idlesplitpants0001_RL.c: idlesplitpants0001.bmp
	$(BMP2AGB) $@ $<
idlesplitpants0003_RL.c: idlesplitpants0003.bmp
	$(BMP2AGB) $@ $<
idlesplitpants0005_RL.c: idlesplitpants0005.bmp
	$(BMP2AGB) $@ $<
idlesplitpants0007_RL.c: idlesplitpants0007.bmp
	$(BMP2AGB) $@ $<
idlesplitpants0009_RL.c: idlesplitpants0009.bmp
	$(BMP2AGB) $@ $<
idlesplitpants0011_RL.c: idlesplitpants0011.bmp
	$(BMP2AGB) $@ $<
idlesplitpants0013_RL.c: idlesplitpants0013.bmp
	$(BMP2AGB) $@ $<
idlesplitpants0015_RL.c: idlesplitpants0015.bmp
	$(BMP2AGB) $@ $<
idlesplitpants0017_RL.c: idlesplitpants0017.bmp
	$(BMP2AGB) $@ $<
idlesplitpants0019_RL.c: idlesplitpants0019.bmp
	$(BMP2AGB) $@ $<
idlesplitpants0021_RL.c: idlesplitpants0021.bmp
	$(BMP2AGB) $@ $<
idlesplitpants0023_RL.c: idlesplitpants0023.bmp
	$(BMP2AGB) $@ $<
idleweapon0001_RL.c: idleweapon0001.bmp
	$(BMP2AGB) $@ $<
idleweapon0003_RL.c: idleweapon0003.bmp
	$(BMP2AGB) $@ $<
idleweapon0005_RL.c: idleweapon0005.bmp
	$(BMP2AGB) $@ $<
idleweapon0007_RL.c: idleweapon0007.bmp
	$(BMP2AGB) $@ $<
idleweapon0009_RL.c: idleweapon0009.bmp
	$(BMP2AGB) $@ $<
idleweapon0011_RL.c: idleweapon0011.bmp
	$(BMP2AGB) $@ $<
idleweapon0013_RL.c: idleweapon0013.bmp
	$(BMP2AGB) $@ $<
idleweapon0015_RL.c: idleweapon0015.bmp
	$(BMP2AGB) $@ $<
idlewigglearms0001_RL.c: idlewigglearms0001.bmp
	$(BMP2AGB) $@ $<
idlewigglearms0003_RL.c: idlewigglearms0003.bmp
	$(BMP2AGB) $@ $<
idlewigglearms0005_RL.c: idlewigglearms0005.bmp
	$(BMP2AGB) $@ $<
idlewigglearms0007_RL.c: idlewigglearms0007.bmp
	$(BMP2AGB) $@ $<
idlewigglearms0009_RL.c: idlewigglearms0009.bmp
	$(BMP2AGB) $@ $<
idlewigglearms0011_RL.c: idlewigglearms0011.bmp
	$(BMP2AGB) $@ $<
idlewigglearms0013_RL.c: idlewigglearms0013.bmp
	$(BMP2AGB) $@ $<
idlewigglearms0015_RL.c: idlewigglearms0015.bmp
	$(BMP2AGB) $@ $<
idlewind0001_RL.c: idlewind0001.bmp
	$(BMP2AGB) $@ $<
idlewind0003_RL.c: idlewind0003.bmp
	$(BMP2AGB) $@ $<
idlewind0005_RL.c: idlewind0005.bmp
	$(BMP2AGB) $@ $<
idlewind0007_RL.c: idlewind0007.bmp
	$(BMP2AGB) $@ $<
idlewind0009_RL.c: idlewind0009.bmp
	$(BMP2AGB) $@ $<
idlewind0011_RL.c: idlewind0011.bmp
	$(BMP2AGB) $@ $<
idlewind0013_RL.c: idlewind0013.bmp
	$(BMP2AGB) $@ $<
idlewind0015_RL.c: idlewind0015.bmp
	$(BMP2AGB) $@ $<
jumpend0001_RL.c: jumpend0001.bmp
	$(BMP2AGB) $@ $<
jumpend0003_RL.c: jumpend0003.bmp
	$(BMP2AGB) $@ $<
karate0001_RL.c: karate0001.bmp
	$(BMP2AGB) $@ $<
karate0003_RL.c: karate0003.bmp
	$(BMP2AGB) $@ $<
karate0005_RL.c: karate0005.bmp
	$(BMP2AGB) $@ $<
karate0007_RL.c: karate0007.bmp
	$(BMP2AGB) $@ $<
karate0009_RL.c: karate0009.bmp
	$(BMP2AGB) $@ $<
karate0011_RL.c: karate0011.bmp
	$(BMP2AGB) $@ $<
karate0013_RL.c: karate0013.bmp
	$(BMP2AGB) $@ $<
karate0015_RL.c: karate0015.bmp
	$(BMP2AGB) $@ $<
netfirelob0001_RL.c: netfirelob0001.bmp
	$(BMP2AGB) $@ $<
netfirelob0003_RL.c: netfirelob0003.bmp
	$(BMP2AGB) $@ $<
netfirelob0005_RL.c: netfirelob0005.bmp
	$(BMP2AGB) $@ $<
netfirelob0007_RL.c: netfirelob0007.bmp
	$(BMP2AGB) $@ $<
netfirelob0009_RL.c: netfirelob0009.bmp
	$(BMP2AGB) $@ $<
netfirelob0011_RL.c: netfirelob0011.bmp
	$(BMP2AGB) $@ $<
netfirelob0013_RL.c: netfirelob0013.bmp
	$(BMP2AGB) $@ $<
netfirelob0015_RL.c: netfirelob0015.bmp
	$(BMP2AGB) $@ $<
netswipe0001_RL.c: netswipe0001.bmp
	$(BMP2AGB) $@ $<
netswipe0003_RL.c: netswipe0003.bmp
	$(BMP2AGB) $@ $<
netswipe0005_RL.c: netswipe0005.bmp
	$(BMP2AGB) $@ $<
netswipe0007_RL.c: netswipe0007.bmp
	$(BMP2AGB) $@ $<
netswipe0009_RL.c: netswipe0009.bmp
	$(BMP2AGB) $@ $<
netswipe0011_RL.c: netswipe0011.bmp
	$(BMP2AGB) $@ $<
netswipe0013_RL.c: netswipe0013.bmp
	$(BMP2AGB) $@ $<
netswipe0015_RL.c: netswipe0015.bmp
	$(BMP2AGB) $@ $<
run0000_RL.c: run0000.bmp
	$(BMP2AGB) $@ $<
run0001_RL.c: run0001.bmp
	$(BMP2AGB) $@ $<
run0002_RL.c: run0002.bmp
	$(BMP2AGB) $@ $<
run0003_RL.c: run0003.bmp
	$(BMP2AGB) $@ $<
run0004_RL.c: run0004.bmp
	$(BMP2AGB) $@ $<
run0005_RL.c: run0005.bmp
	$(BMP2AGB) $@ $<
run0006_RL.c: run0006.bmp
	$(BMP2AGB) $@ $<
run0007_RL.c: run0007.bmp
	$(BMP2AGB) $@ $<
run0008_RL.c: run0008.bmp
	$(BMP2AGB) $@ $<
run0009_RL.c: run0009.bmp
	$(BMP2AGB) $@ $<
run0010_RL.c: run0010.bmp
	$(BMP2AGB) $@ $<
run0011_RL.c: run0011.bmp
	$(BMP2AGB) $@ $<
run0012_RL.c: run0012.bmp
	$(BMP2AGB) $@ $<
run0013_RL.c: run0013.bmp
	$(BMP2AGB) $@ $<
run0014_RL.c: run0014.bmp
	$(BMP2AGB) $@ $<
run0015_RL.c: run0015.bmp
	$(BMP2AGB) $@ $<
soakup0001_RL.c: soakup0001.bmp
	$(BMP2AGB) $@ $<
soakup0003_RL.c: soakup0003.bmp
	$(BMP2AGB) $@ $<
soakup0005_RL.c: soakup0005.bmp
	$(BMP2AGB) $@ $<
soakup0007_RL.c: soakup0007.bmp
	$(BMP2AGB) $@ $<
teeterfront0001_RL.c: teeterfront0001.bmp
	$(BMP2AGB) $@ $<
teeterfront0003_RL.c: teeterfront0003.bmp
	$(BMP2AGB) $@ $<
teeterfront0005_RL.c: teeterfront0005.bmp
	$(BMP2AGB) $@ $<
teeterfront0007_RL.c: teeterfront0007.bmp
	$(BMP2AGB) $@ $<
teeterfront0009_RL.c: teeterfront0009.bmp
	$(BMP2AGB) $@ $<
teeterfront0011_RL.c: teeterfront0011.bmp
	$(BMP2AGB) $@ $<
teeterfront0013_RL.c: teeterfront0013.bmp
	$(BMP2AGB) $@ $<
teeterfront0015_RL.c: teeterfront0015.bmp
	$(BMP2AGB) $@ $<
walkforward0001_RL.c: walkforward0001.bmp
	$(BMP2AGB) $@ $<
walkforward0003_RL.c: walkforward0003.bmp
	$(BMP2AGB) $@ $<
walkforward0005_RL.c: walkforward0005.bmp
	$(BMP2AGB) $@ $<
walkforward0007_RL.c: walkforward0007.bmp
	$(BMP2AGB) $@ $<
walkforward0009_RL.c: walkforward0009.bmp
	$(BMP2AGB) $@ $<
walkforward0011_RL.c: walkforward0011.bmp
	$(BMP2AGB) $@ $<
walkforward0013_RL.c: walkforward0013.bmp
	$(BMP2AGB) $@ $<
walkforward0015_RL.c: walkforward0015.bmp
	$(BMP2AGB) $@ $<

clean:
	-rm $(TARGET_ARC) $(.OFILES) $(.CFILES)
